# Generated by Django 3.1.3 on 2024-07-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patientinfo',
            fields=[
                ('date', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('phone', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('marital_status', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('disease', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=100)),
            ],
        ),
    ]
