# Generated by Django 3.1.3 on 2024-07-16 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospAdmin', '0003_doctorinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorinfo',
            name='user_name',
        ),
    ]
