# Generated by Django 3.1.3 on 2024-07-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospAdmin', '0004_remove_doctorinfo_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinfo',
            name='user_name',
            field=models.CharField(default='default_user_name', max_length=100),
        ),
    ]
