# Generated by Django 3.1.3 on 2024-07-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospAdmin', '0005_doctorinfo_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceptionistInfo',
            fields=[
                ('joining_date', models.DateField()),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('user_name', models.CharField(default='default_user_name', max_length=100)),
                ('age', models.IntegerField()),
                ('marital_status', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=100)),
            ],
        ),
    ]
