# Generated by Django 3.1.3 on 2024-07-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospAdmin', '0006_receptionistinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(max_length=100)),
                ('patient_id', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=100)),
                ('disease', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
